### ISSUE TITLE
[ove-util-libs] + [ove-core] Logger and utils are duplicated 

### ISSUE THREAD

**Issue by oserban** [ove/ove#14] opened 2018-10-15 09:03 UTC
The ove-util-libs code is duplicated into ove-core

**Comment by senakafdo** [comment] 2018-10-15 09:28
@oserban, yes, I just explained the same on that issue. I will resolve both of these together, this issue now being a duplicate of #13.

**Closed** 2018-10-15 09:30 UTC
Labels: duplicate
