### ISSUE TITLE
True black background

### ISSUE THREAD

**Issue by davidbirchwork** [ove/ove#31] opened 2018-11-05 14:51 UTC
Please can we change the OVE Background to be true black

**Comment by senakafdo** [comment] 2018-11-05 21:11
@davidbirchwork, the background can be changed by setting a background colour of your choice. It is a mistake to enforce true black backgrounds to apps. In OVE all apps have transparent backgrounds and the person who develops the visualisation can set a background colour of their choice. Some visualisations that have already been developed with OVE us black backgrounds while others have a background that blends well with its foreground colours.

I am resolving this issue as it is invalid. If you need to fix any visualisations to have black backgrounds please explain your reasons behind it and report under the relevant issue tracker(s).

**Comment by davidbirchwork** [comment] 2018-11-09 15:17
@senakafdo I understand these points. 

I would however argue that this justification has in mind the wrong users - 

The real users of OVE are **not** us as developers but our users - the people learning and conducting research by seeing and interacting with content presented in OVE. 

For these people, our real users, a black background is clearer due to its higher contrast, less distracting as it hides bezels and will appear more professional. 
These people don't (&shouldn't) care that about whether they can tell if the system is running properly. 

what does everyone think?

**Comment by senakafdo** [comment] 2018-11-09 15:57
@davidbirchwork, do you want to hide the bezels when OVE is displaying no content or when it is displaying some content? I speak on behalf of an average user who will never understand whether OVE is running or not if the background is black. The background you refer to is what you get when OVE runs by itself with no content.

**Comment by davidbirchwork** [comment] 2018-11-09 16:08
@senakafdo why would an average user (a visitor who comes into the observatory) ever need to care whether OVE is running or not? ;)

**Comment by senakafdo** [comment] 2018-11-09 16:10
@davidbirchwork, I dont see anything that is required to be fixed here. I have explained the reason why this has been implemented in a specific way and there is a purpose for doing that. I am therefore resolving this issue.

**Closed by senakafdo** 2018-11-09 16:10 UTC
Labels: wont fix

**Comment by senakafdo** [comment] 2018-11-09 19:57
As discussed with the team, I have created a new issue for changing the background colour and setting a logo - which is also supported by comparable some software systems. Hardcoding the colour to black was FTR confirmed to be not required.
